#ifndef UI_UPDATETYPES_H
#define UI_UPDATETYPES_H

enum class UI_UpdateType {
    AFTER_FETCH_SUCCESS,
    UPDATE_GROUP_CHAT,
    NEW_MESSAGE_SUCCESS,
    NEW_INSTANT_CALL,
    NEW_SCHEDULED_CALL,
    JOIN_CALL,
    LOG_IN_FAILED,
    REGISTRATION_FAILED,
    REGISTRATION_SUCCEEDED
};

#endif // UI_UPDATETYPES_H
